#pragma once
#include <ImGUI/imgui.h>
#include <ImGUI/imgui_impl_opengl3.h>
#include <ImGUI/imgui_impl_glfw.h>
#include <GLEW/include/GL/glew.h>
#include <GLFW/include/GLFW/glfw3.h>
#include <vector>
#include <string>
#include <functional>