#pragma once
#include <cstdint>
#include <string>
#include <windows.h>
#include <CyCode/cyTriMesh.h>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>
#include <Graphics/Graphics.h>