#pragma once
#include <cstdint>
#include <string>
#include <GLEW/include/GL/glew.h>
#include <FreeGLUT/include/GL/freeglut.h>
#include <CyCode/cyTriMesh.h>
#include <CyCode/cyGL.h>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>